name: Jere the Dog
favicon: null
layout_spectrum: 0.5381493552122265
typography_spectrum: 0.7461832906119525
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9152544722892344
  lightness: 0.620367581024766
  saturation: 0.1177458802703768
  rhythmicContrast: 0.577822336461395
purpose: []
